---
services:
  - docker

env:
  - distro: centos7
  - distro: centos6
  - distro: debian8
  - distro: ubuntu1604
  - distro: ubuntu1404

script:
  # Download test shim, clone of geerlingguy's
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/uZer/990587ff11255f9afdfbea9d79c3297e/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests without nodocker tags
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
