---
- name: Copy 389 ldap template
  template:
    src: "dirsrv.inf.j2"
    dest: /root/dirsrv.inf
    owner: root
    group: root
    mode: '0700'
  tags:
    - configure

- stat:
    path: "/etc/dirsrv/slapd-{{ dirsrv_server_id }}"
  register: p
  check_mode: no
  failed_when: false
  changed_when: false
  tags:
    - configure

- name: Configure LDAP if /etc/dirsrv/slapd-{{ dirsrv_server_id }} doesn't exist yet.
  shell: >
    {{ dirsrv_setupdsadmin }} --silent --file=/root/dirsrv.inf --logfile=/root/389install.log
  when: not (p.stat.isdir is defined)
  tags:
    - configure

# vim:ft=ansible:
