---
- name: Install 389ds packages (apt)
  apt:
    name: "{{ dirsrv_packages }}"
    state: "{{ dirsrv_package_state }}"
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  tags:
    - install

- name: Install 389ds packages (yum)
  yum:
    name: "{{ dirsrv_packages }}"
    state: "{{ dirsrv_package_state }}"
  when: ansible_os_family == "RedHat"
  tags:
    - install
# vim:ft=ansible:
