---
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
  tags:
    - install
    - server
    - configure

- include: install.yml
- include: server_config.yml
- include: dirsrv_config.yml

- meta: flush_handlers

- name: Ensure 389dirsrv is started and enabled
  service:
    name: "{{ dirsrv_service_name }}"
    state: started
    enabled: yes
  tags:
    - install
    - server
    - configure

- name: Ensure 389dirsrv admin is started and enabled
  service:
    name: "{{ dirsrv_admin_service_name }}"
    state: started
    enabled: yes
  tags:
    - install
    - server
    - configure
# vim:ft=ansible:
