---
- name: Create dirsrv group if needed
  group:
    name: "{{ dirsrv_group }}"
    gid: 389
    state: present
  tags:
    - server

- name: Create dirsrv users if needed
  user:
    name: "{{ dirsrv_user }}"
    state: present
    uid: 389
    shell: /usr/sbin/nologin
    home: /var/lib/dirsrv
    group: "{{ dirsrv_group }}"
  tags:
    - server

- name: Configure systemctl variables for tcp optimisation
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: net.ipv4.tcp_keepalive_time, value: 300 }
    - { name: net.ipv4.ip_local_port_range, value: "1024 65000" }
  when: dirsrv_manage_tcp
  tags:
    - server
    - nodocker

- name: Configure systemctl variables for max files
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: fs.file-max, value: 64000 }
  when: dirsrv_manage_filemax
  tags:
    - server
    - nodocker

- name: Configure file limits for dirsrv service (sysv/init/not systemd)
  ini_file:
    dest: /etc/sysconfig/dirsrv
    section: 'Service'
    option: 'LimitNOFILE'
    value: '8192'
    state: present
  when: >
    dirsrv_manage_filemax and
    ansible_os_family == "RedHat" and
    ansible_service_mgr != "systemd"
  tags:
    - server

- name: Configure file limits for dirsrv service (systemd) (redhat based)
  lineinfile:
    dest: /etc/sysconfig/dirsrv.systemd
    state: present
    insertafter: "^[Service]"
    line: "LimitNOFILE=8192"
    regexp: "^LimitNOFILE"
  when: >
    dirsrv_manage_filemax and
    ansible_service_mgr == "systemd" and
    ansible_os_family == "RedHat"
  notify:
    - daemon-reload
    - restart dirsrv
    - restart dirsrv-admin
  tags:
    - server

- name: Configure file limits for dirsrv service (systemd) (debian based)
  lineinfile:
    dest: /etc/default/dirsrv.systemd
    state: present
    insertafter: "^[Service]"
    line: "LimitNOFILE=8192"
    regexp: "^LimitNOFILE"
  when: >
    dirsrv_manage_filemax and
    ansible_service_mgr == "systemd" and
    ansible_os_family == "Debian"
  notify:
    - daemon-reload
    - restart dirsrv
    - restart dirsrv-admin
  tags:
    - server

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737214
# - name: Debian 8 fix for libsoftiken3.so
#   shell: >
#     cd /usr/lib/i386-linux-gnu/
#     ln -s /usr/lib/i386-linux-gnu/nss/libsoftokn3.so
#     ldd /usr/lib/i386-linux-gnu/dirsrv/cgi-bin/config
#   when: >
#     ansible_distribution == "Debian" and
#     ansible_distribution_major_version == "8"
# vim:ft=ansible:
