---
- name: Create dirsrv group if needed
  group:
    name: "{{ dirsrv_group }}"
    gid: 389
    state: present
  tags:
    - server

- name: Create dirsrv users if needed
  user:
    name: "{{ dirsrv_user }}"
    state: present
    uid: 389
    shell: /usr/sbin/nologin
    home: /var/lib/dirsrv
    group: "{{ dirsrv_group }}"
  tags:
    - server

- name: Configure systemctl variables for tcp optimisation
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: net.ipv4.tcp_keepalive_time, value: 300 }
    - { name: net.ipv4.ip_local_port_range, value: "1024 65000" }
  when: dirsrv_manage_tcp
  tags:
    - server
    - nodocker

- name: Configure systemctl variables for max files
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: fs.file-max, value: 64000 }
  when: dirsrv_manage_filemax
  tags:
    - server
    - nodocker

- name: Configure file limits for dirsrv service (sysv/init/not systemd)
  ini_file:
    dest: /etc/sysconfig/dirsrv
    section: 'Service'
    option: 'LimitNOFILE'
    value: '8192'
    state: present
  when: >
    dirsrv_manage_filemax and
    ansible_os_family == "RedHat" and
    ansible_service_mgr != "systemd"
  tags:
    - server

- name: Configure file limits for dirsrv service (systemd)
  lineinfile:
    dest: /etc/sysconfig/dirsrv.systemd
    state: present
    insertafter: "^[Service]"
    line: "LimitNOFILE=8192"
    regexp: "^LimitNOFILE"
  when: >
    dirsrv_manage_filemax and
    ansible_service_mgr == "systemd"
  notify:
    - daemon-reload
    - restart dirsrv
    - restart dirsrv-admin
  tags:
    - server
# vim:ft=ansible:
