---
- name: restart dirsrv
  service:
    name: "{{ dirsrv_service_name }}"
    state: restarted

- name: restart dirsrv-admin
  service:
    name: "{{ dirsrv_admin_service_name }}"
    state: restarted

# Before ansible 2.4
- name: daemon-reload
  systemd:
    daemon_reload: yes
    name: "{{ dirsrv_service_name }}"
    state: restarted

# Preparing Ansible 2.4
#- name: daemon-reload
#  systemd:
#    daemon_reload: yes
# vim:ft=ansible:
